---
- become: yes
  hosts: all
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', pub_key) }}"


